### ISSUE TITLE
Add highway to road types

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-tracing-guide#17]
Based on discussions with GATE and @jimmyrocks looks like we'll be supporting motorways which needs to be added to the guide.

**Comment by chadlawlis** [comment]
![motorway_highway](https://cloud.githubusercontent.com/assets/1238636/9145537/64b098ee-3d12-11e5-965e-fd4f00b95ead.jpg)

Changing title because... America. :us: :us: :us:

**Comment by chadlawlis** [comment]
Closing this here and adding to Road section updates/additions here https://github.com/nationalparkservice/places-tracing-guide/issues/18
