### ISSUE TITLE
GIF for digitizing bridge is incorrect

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-tracing-guide#2]
Rather than going back and selecting the "Bridge" preset, you should just select "Bridge" underneath the attributes after a segment is split out from a larger segment and then selected.

**Comment by chadlawlis** [comment]
Done: [http://nationalparkservice.github.io/places-tracing-guide/#bridge](http://nationalparkservice.github.io/places-tracing-guide/#bridge)
