### ISSUE TITLE
Replace "optional fields" dropdown content with current editor optional presets

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-tracing-guide#22]
The guide's "optional fields" dropdown currently shows a list of outdated tags. Replace these with the current optional presets in the editor, using the preset title instead of the tag.

**Comment by jimmyrocks** [comment]
Yes. you will need to use the field title and the tags within it.
I am working on generating the data for the places-tagging-guide

**Comment by chadlawlis** [comment]
I think I am going to stay away from listing the tags for each optional field (using only the title as it appears in editor) but maintain the link to their respective OSM wiki. The less exposure to the underlying tagging schema the better here...

**Comment by chadlawlis** [comment]
Update on this: we are moving away from including OSM wikis, so these will not be included with the optional fields.

Add optional fields to the spreadsheet [here](https://docs.google.com/spreadsheets/d/1XFqkmIYMEp73q9flgNto9QJim6N5hbacgkUAgdf0rhE/edit#gid=0) under `optionalTags` for implementation using the new `.json` files, once they are ready to go.
