### ISSUE TITLE
Emphasize nps.gov data priorities

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-tracing-guide#24]
1. Visitor centers
2. Park districts
3. Entrance stations
4. Trails, including trailheads
5. Campgrounds
6. everything else

**Comment by chadlawlis** [comment]
Reordered points of interest based on NPS.gov priority and added a disclaimer to the POI section header for the webinar (https://github.com/nationalparkservice/places-tracing-guide/commit/3aff6776e618af485595a0dbe72c61ecb612e13d + https://github.com/nationalparkservice/places-tracing-guide/commit/9249a96350c6cdcc23591da9fe9da3306077b450).

I'd like to make these priorities a little more obvious on the page, so keeping this open for now.

**Comment by chadlawlis** [comment]
Closing out - added to [POI](https://github.com/nationalparkservice/places-tracing-guide/commit/ee1aa85dd3fa7c25c0f6719caec734d3d4940e85) and [Trails](https://github.com/nationalparkservice/places-tracing-guide/commit/30182b99ba28a3d909cbe1734e256298fc82e503) section headers.
