### ISSUE TITLE
Places tracing guide not accessible

### ISSUE THREAD

**Issue by frogmapr** [nationalparkservice/places-tracing-guide#28]
When I try to access: http://insidemaps.nps.gov/places/tracing-guide/ it isn't working, this is the URL that the places editor site wants to point to. Did it move?

**Comment by nateirwin** [comment]
Yep, it's here now: https://www.nps.gov/maps/tools/places/tracing-guide/

**Comment by chadlawlis** [comment]
It's been a while since the content was updated @frogmapr so don't hesitate to reach out with any data-specific questions (tracing, tagging, etc). I plan on spending some time getting it back up to date at some point here soon.
