### ISSUE TITLE
Tracing Guide Feedback

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-tracing-guide#3]
Now that the first iteration of the guide is complete (with the exception of a few final GIFs), please submit any feedback here.

**Comment by makella** [comment]
I think it would be good to talk about the 'Park Tiles Rendering' piece.  We need to think about Park Tiles as almost separate because the POIs are not burnt into the basemap.  So if someone expects that they are going to see these icons when they access Park Tiles in Builder, they aren't (at least for now).  

Maybe another way to say it is Cartographic Rendering or Map Rendering?  I'm not exactly sure what is best and think it would be a good discussion for us to have.

Also, the POIs that are on the guide are not all represented on the Park Tiles POI overlay... should they be?  If so, let us know.

**Comment by jakecoolidge** [comment]
Chad and I talked about this, but I'll capture it here: 

For the parking section: one idea is to remove paragraphs 2 and 3 from the first section, as these instructions echo instructions in the subsequent sections, and move the point, line, and area images to the subsequent Parking Amenity and Parking Aisle sections. 

I think the separation of information in the Trails section is more intuitive to me. You begin with broad/entry-level info, and then elaborate later on--especially helpful when the mapper has more robust information to add to each trail.

**Comment by makella** [comment]
Small thing: the visitor center icon that you have in the doc is not the same one that is rendered on the Park Tiles POI overlay... Jake can get you the one that we use for consistency.

I'll actually read through more of the guide these are just some small observations!

**Comment by chadlawlis** [comment]
@makella in reference to [Park Tiles Rendering](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111213405):

Good question, thanks for pointing that out. Changing to `Map Rendering` or `Places Rendering` makes sense here - the intention was to show the user how the icon will appear on the map in Places editor, not Park Tiles. I'm always tempted to mention Park Tiles when discussing any form of our map rendering, so good catch.

I'm not sure about needing to represent these POIs in the Park Tiles overlay, although they are some of the most common added to Places so it might make sense? Is there a list of the POIs available in the overlay I could take a look at?

**Comment by chadlawlis** [comment]
@makella in reference to the [VC icon](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111213713):

If you or @jakecoolidge could point me to the most recent icon that would be great. I've been pulling the icons from [here](https://github.com/nationalparkservice/npmaki/tree/gh-pages/renders).

**Comment by chadlawlis** [comment]
@jakecoolidge in reference to the [Parking section](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111213480):

This makes sense to me, although I have been listing the tools (`Area`, `Point`, and `Line`) in the introductory sections for each data type so I would like to try to keep that consistent to the extent possible. I definitely agree with your point about overlap/repetition of information from the introductory section to the `Parking (amenity)` and `Parking Aisle` sub-sections, so I will look to cut that down/remove it.

**Comment by makella** [comment]
Hey Chad, that is an excellent way to determine what should be drawn in the Park Tiles POI overlay.  If there are particular features that are being added most to Places, yes! let's get those on the map!  That means they are important and the users are telling us that by adding them. I really like that as a measure of what we should display.

We currently symbolize:
- Visitor Center
- Ranger Station
- Information
- Campground
- Campsite
- Picnic Area
- Food Service
- Lodging
- Store
- Trailhead
- Shelter
- Parking
- Restroom

**Comment by jakecoolidge** [comment]
@cwlawlis802: Our symbol repos need work. I was going to put the symbols that we use as overlays in Park Tiles in NPMaki, but I got tripped up--mainly because this is still a fork of Maki, so my pull request isn't set up right...(insert boring details). Instead, I'm hosting stuff here until we can get this sorted out:

https://github.com/nationalparkservice/symbol-library/tree/master/svg-set-comprehensive

If you have any questions on this repo, let me know.

**Comment by nateirwin** [comment]
The description for "Unclassified Road states, "It is of lower importance than a tertiary road..." But we aren't collecting tertiary roads. Should "tertiary road" be changed to "secondary road"?

**Comment by nateirwin** [comment]
I know you took most of the first few paragraphs from existing text, but I recently had a conversation with someone in the NPS who recommended that we stop using the phrase "internal crowd-sourcing" altogether. He said we should say something more like "we've opened data collection so more people can contribute." Apparently "crowd-sourcing" worries some in leadership, and they end up focusing on that and not on the positives.

Just a thought.

**Comment by nateirwin** [comment]
Rather than just saying "Start mapping now!" at the top, perhaps we should say, "If you are on the NPS network, start mapping now!" (or something like that).

**Comment by nateirwin** [comment]
It looks like some of NPS Bootstrap's fonts are getting overridden by styles set in `style.css`. In particular, line 13:

```
body,
h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: "Lato","Helvetica Neue",Helvetica,Arial,sans-serif;
  font-weight: 700;
}
```

does not need to be there.

**Comment by chadlawlis** [comment]
@makella in reference to [POI Park Tiles overlay](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111221456):

Below are the top 20 POIs (by tag count) in Places, which might help inform any additions to the overlay list. I think it would be worthwhile for the POI overlay to mirror the primary POIs listed in the guide (or vice versa), so the most common information users are adding to the map are available for use as well.
1. Campground; 2025; `{"tourism":"camp_site"}`
2. Parking; 1394; `{"amenity":"parking"}`
3. Picnic Area; 1167; `{"tourism":"picnic_site"}`
4. Restroom; 725; `{"amenity":"toilets"}`
5. Trailhead; 460; `{"highway":"trailhead"}`
6. Visitor Center; 418; `{"tourism":"information, "information":"office"}`
7. Ranger Station; 374; `{"amenity":"ranger_station"}`
8. Boat Launch; 363; `{"leisure":"slipway"}`
9. Office; 305; `{"building":"office"}`
10. Office; 305; `{"office":"*"}`
11. Canoe Access; 155; `{"access":"canoe"}`
12. Food Service; 125; `{"amenity":"food_court"}`
13. Wheelchair Accessible; 108; `{"wheelchair":"yes"}`
14. Lodging; 98; `{"tourism":"hotel"}`
15. Telephone; 84; `{"amenity":"telephone"}`
16. Entrance Station; 82; `{"barrier":"entrance"}`
17. Drinking Water; 79; `{"amenity":"drinking_water"}`
18. Waterfall; 78; `{"waterway":"waterfall"}`
19. Swimming Area; 72; `{"sport":"swimming"}`
20. Information; 65; `{"tourism":"information"}`

Let me know if there are any you are thinking of including in the overlay that are not in the guide and I can add those in as well.

**Comment by chadlawlis** [comment]
@jakecoolidge in reference to [symbols](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111228072):

Is there a VC icon in there? Can't seem to find it.

**Comment by jakecoolidge** [comment]
@cwlawlis802 sorry about that. It's there now.

It's meant to be comprehensive in the near future, but I haven't created all the svgs from the source Illustrator files yet.

**Comment by chadlawlis** [comment]
@nateirwin re: [unclassified road description](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111250154): :heavy_check_mark: (changed to secondary road)

re: [crowd-sourcing](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111252681) what do you think about:

> Places is an internal data collection system for the National Park Service's "core" geospatial data.

compared to the original

> Places is an internal crowd-sourcing system for the National Park Service's "core" geospatial data.

re: [start mapping now](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111256448) what do you think about this:

![start_mapping_now](https://cloud.githubusercontent.com/assets/1238636/8117620/80556eea-1057-11e5-9e9b-5ea6208ada5b.jpg)

and finally re: [fonts](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111257042) :heavy_check_mark: good catch!

**Comment by chadlawlis** [comment]
@jakecoolidge great, [got it](https://github.com/nationalparkservice/symbol-library/blob/master/svg-set-comprehensive/visitor-center-black-32.svg) - thanks!

**Comment by nateirwin** [comment]
Looks good to me!

**Comment by chadlawlis** [comment]
@jakecoolidge (re: [parking](https://github.com/nationalparkservice/places-tracing-guide/issues/3#issuecomment-111213480)) take a look at the [update to the parking description](https://github.com/nationalparkservice/places-tracing-guide/commit/4baf55940f1025e5e22f49187f089e859f4b8d7a) and let me know what you think. Live on the site [here](http://nationalparkservice.github.io/places-tracing-guide/#parking).

**Comment by chadlawlis** [comment]
@makella all set with the [updated VC icon](http://nationalparkservice.github.io/places-tracing-guide/#visitor_center) pulling from the [symbol library repo](https://github.com/nationalparkservice/symbol-library/tree/master/svg-set-comprehensive) :heavy_check_mark:

**Comment by jakecoolidge** [comment]
@cwlawlis802: looks good. I think the parking section is done once the images are up.

**Comment by chadlawlis** [comment]
@jakecoolidge great, thanks for the feedback

**Comment by nateirwin** [comment]
I don't see parking aisle in the tracing guide. It should be there, right?

**Comment by chadlawlis** [comment]
@nateirwin it's in there: [http://nationalparkservice.github.io/places-tracing-guide/#parking_aisle](http://nationalparkservice.github.io/places-tracing-guide/#parking_aisle)

**Comment by nateirwin** [comment]
Ah, great. Guess I figured it would be under the roads section. That leads to another thought: Can we document our recommendation(s) for road, trail, and parking lot topologies? For example, do we recommend that trails connect to roads? And do we recommend bringing a primary, secondary, or service road and connecting it to the entrance of a parking lot and then using either service road or parking aisle in the parking lot itself?

**Comment by chadlawlis** [comment]
@nateirwin sure, can do. This is probably something we should think through before I write it up. So, let's discuss this in the [issue I created](https://github.com/nationalparkservice/places-data/issues/54). I'll do a little research to see how this is handled in OSM and make initial recommendations, which I will seek feedback on for a general consensus.

On first thought I am assuming yes to trails connecting to roads and yes to using a service road to connect to the entrance of a parking lot and then parking aisles inside of the parking lot.

**Comment by tpcolson** [comment]
The IRMA Data Store records (https://irma.nps.gov/App/Reference/Profile/2222347) contain extracts in 4 formats (geojson, shape, kml, csv)...the links to download just geojson in the 3rd paragraph should point to the metadata records, each of which have a link for each of the 4 download types. As this is the landing page for most NPS access to the system, want to make sure not to alienate folks whom aren't familiar with geojson and how to use it. Or....include reference that other formats are supported and link, else where on this page, to those downloads.....actually, this one link will give you everything in all formats...https://irma.nps.gov/App/Reference/GroupedProducts?parentReferenceCode=2222347

**Comment by nateirwin** [comment]
Added links to the IRMA records to the public Places landing page: http://www.nps.gov/npmap/tools/places/. Does that take care of what you are looking for, @tpcolson?

**Comment by tpcolson** [comment]
perfect

**Comment by tpcolson** [comment]
This is really nit-picky....but the links to the OSM Wiki pages, e.g for "maxspeed=" goes to directly to http://wiki.openstreetmap.org/wiki/Key:maxspeed....these should either open in a new window...or...should have the standard "Leaving the NPS web page" notice .....

**Comment by jimmyrocks** [comment]
Tom, we actually looking at changing all of those OSM Wiki links to point
to the tracing guide. It can be a little confusing to push people out to
OpenStreetMap while they're using our editor.

**Comment by nateirwin** [comment]
Closing for now. I think we've addressed everything covered in this issue either directly in the tracing guide or in another open issue.
