### ISSUE TITLE
Spelin mistace 

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-tracing-guide#8]
http://nationalparkservice.github.io/places-tracing-guide/#about

"The Places editor is built using OpenStreetMap's iD editor. Check out learnOSM's iD editor walthrough to familiarize yourself..."

walthrough missing a k.....

**Comment by chadlawlis** [comment]
Thanks Tom, [all set](https://github.com/nationalparkservice/places-tracing-guide/commit/bb97df90490a0ff7093856bf29243ac7a3fa60bf).
