### ISSUE TITLE
Add file name to extract links in http://www.nps.gov/npmap/tools/places/

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-tracing-guide#9]
The CartoDB Extract link should have the file name option e.g. https://nps.cartodb.com/api/v2/sql?format=shp&q=SELECT+*+FROM+points_of_interest would be https://nps.cartodb.com/api/v2/sql?filename=NPS_POIS&format=shp&q=SELECT+*+FROM+points_of_interest

**Comment by nateirwin** [comment]
Done.
